name: Push to Telegram
on:
  push:
    branches: [ main, develop ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}  # ID —á–∞—Ç–∞
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # —Ç–æ–∫–µ–Ω –±–æ—Ç–∞
        message: |
          "üöÄ Push –≤ ${{ github.repository }} by ${{ github.actor }}"
          **–í–µ—Ç–∫–∞:** ${{ github.ref_name }}
          **–ö–æ–º–º–∏—Ç:** ${{ github.sha }}
          **–ê–≤—Ç–æ—Ä:** ${{ github.actor }}
          **–°–æ–æ–±—â–µ–Ω–∏–µ:** ${{ github.event.head_commit.message }}
          
          üîó ${{ github.event.head_commit.url }}
