name: Push to Telegram
on:
  push:
    branches: [ main, develop ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.8430017466 }}  # ID —á–∞—Ç–∞
        token: ${{ secrets.8430017466:AAEW71rfyYUZCAiZibHgISVj3w6glwebdNI }}  # —Ç–æ–∫–µ–Ω –±–æ—Ç–∞
        message: |
          üöÄ **–ù–æ–≤—ã–π –ø—É—à –≤ ${{ github.repository }}**
          
          **–í–µ—Ç–∫–∞:** ${{ github.ref_name }}
          **–ö–æ–º–º–∏—Ç:** ${{ github.sha }}
          **–ê–≤—Ç–æ—Ä:** ${{ github.actor }}
          **–°–æ–æ–±—â–µ–Ω–∏–µ:** ${{ github.event.head_commit.message }}
          
          üîó ${{ github.event.head_commit.url }}
